apiVersion: v1
kind: Service
metadata:
  name: otel-demo-app
  namespace: otel-demo
  labels:
    app: otel-demo-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: otel-demo-app 