apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-demo

resources:
  - namespace.yaml
  - elastic-secret.yaml
  - otel-collector-configmap.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - load-generator-deployment.yaml 