apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-demo
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25
      
      resource:
        attributes:
          - key: service.namespace
            value: "otel-demo"
            action: upsert
          - key: deployment.environment
            value: "production"
            action: upsert

    exporters:
      otlp:
        endpoint: "${ELASTIC_APM_ENDPOINT}"
        headers:
          Authorization: "Bearer ${ELASTIC_APM_TOKEN}"
        tls:
          insecure: false
      
      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp, logging]
        
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp, logging]
        
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp, logging] 